[build]
builder = "NIXPACKS"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.healthcheck]]
path = "/"
timeout = 100

[env]
NODE_ENV = "production"

